---
version: 2
updates:
  - package-ecosystem: docker
    directory: "/all-in-one"
    schedule:
      interval: daily
    reviewers:
      - "EasyDynamics/oscal-editor-reviewers"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - "EasyDynamics/oscal-editor-reviewers"
