name: Build, Test, Deploy
on:
  push:
    branches: 
      - main

jobs:
  build_test_deploy:
    name: Build, Test, and Deploy All-in-One Docker Image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Deployment Code
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout OSCAL React Library
        uses: actions/checkout@v2
        with:
          repository: EasyDynamics/oscal-react-library
          path: viewer

      - name: Checkout OSCAL REST Service
        uses: actions/checkout@v2
        with:
          repository: EasyDynamics/oscal-rest-service
          path: rest-service

      - name: Build OSCAL Viewer
        run: cd example && npm install && npm run build && cp -r build ../main/build
        working-directory: viewer

      - name: Build OSCAL Rest Service
        run: mvn install && cp target/oscal-rest-service-0.0.1-SNAPSHOT.jar ../main
        working-directory: rest-service

      - name: Build Docker Image
        run: docker build --tag easygrc-all-in-one .

      # TODO
      - name: Test Deployment
        run: echo TODO

      #TODO: create an IAM user for this and add the credentials to secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credientials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: OscalDockerRepository
        run: docker push $ECR_REGISTRY/$ECR_REPOSITORY:easygrc-all-in-one
