name: Build, Test, Deploy
on:
  push:
    branches: 
      - main

env:
  IMAGE_NAME: easygrc-all-in-one
  CONTAINER_NAME: test_container

jobs:
  build_test_deploy:
    name: Build, Test, and Deploy All-in-One Docker Image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Deployment Code
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout OSCAL React Library
        uses: actions/checkout@v2
        with:
          repository: EasyDynamics/oscal-react-library
          path: viewer

      - name: Checkout OSCAL REST Service
        uses: actions/checkout@v2
        with:
          repository: EasyDynamics/oscal-rest-service
          path: rest-service

      - name: Build OSCAL Viewer
        run: cd example && npm install && npm run build && cp -r build ../main/build
        working-directory: viewer

      - name: Build OSCAL Rest Service
        run: mvn install && cp target/oscal-rest-service-0.0.1-SNAPSHOT.jar ../main
        working-directory: rest-service

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: $IMAGE_NAME

      - name: Run Docker Container for Tests
        run:
          docker run --rm -p 8080:8080 \
          -v $(pwd)/all-in-one/oscal-content:/app/oscal-content \
          --name $CONTAINER_NAME $IMAGE_NAME

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/OSCAL/OSCAL_URL_Test.spec.js

      - name: Stop Running Container
        run:
          docker stop $CONTAINER_NAME

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Container Registry
        uses: docker/build-push-action@v2
          with:
            push: true
            tags:
              ghcr.io/EasyDynamics/$IMAGE_NAME:latest
