name: Build, Test, Deploy
on:
  push:
    branches: [EGRC-492]
  workflow_dispatch:

env:
  IMAGE_NAME: easygrc-all-in-one
  CONTAINER_NAME: test_container

jobs:
  build_test_deploy:
    name: Build, Test, and Deploy All-in-One Docker Image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Pull the REST service .jar file from the Maven repository
      # and rename it to the filename that the Dockerfile expects
      # TODO: make this filename configurable
      - name: Pull OSCAL REST Service
        run: |
          mvn -X --settings ./settings.xml \
          org.apache.maven.plugins:maven-dependency-plugin:3.2.0:get \
          -Dartifact=com.easydynamics:oscal-rest-service:0.0.1-SNAPSHOT
          mvn org.apache.maven.plugins:maven-dependency-plugin:3.2.0:copy \
          -Dartifact=com.easydynamics:oscal-rest-service:0.0.1-SNAPSHOT:jar \
          -DoutputDirectory=./
        env:
          MAVEN_TOKEN: ${{ secrets.PACKAGE_READ_TOKEN }}

      - name: Pull OSCAL Viewer
        run: |
          echo //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }} > .npmrc
          npm install \
          @easydynamics/oscal-viewer@0.1.1 --registry=https://npm.pkg.github.com

      - name: Build OSCAL Viewer
        run: npm install && npm run build && cp -r build ../build
        working-directory: package

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: $IMAGE_NAME

      - name: Run Docker Container for Tests
        run: |
          docker run --rm -p 8080:8080 \
          -v $(pwd)/all-in-one/oscal-content:/app/oscal-content \
          --name $CONTAINER_NAME $IMAGE_NAME

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/OSCAL/OSCAL_URL_Test.spec.js

      - name: Stop Running Container
        run:
          docker stop $CONTAINER_NAME

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags:
            ghcr.io/EasyDynamics/$IMAGE_NAME:latest
